name: stonks_android
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  font_awesome_flutter: ^10.4.0
  sqflite: 
  path_provider:
  http: ^0.13.6
  syncfusion_flutter_charts: ^21.2.4
  shared_preferences: ^2.1.1
  awesome_notifications: ^0.7.4+1
  internet_connection_checker: ^1.0.0+1
  validators: ^3.0.0
  syncfusion_flutter_datagrid: ^21.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/company_json.json
    - assets/data/nico.json
    - assets/data/airtel.json
